jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        version: '3.3.4'
        channel: 'stable'
    - run: flutter --version
    - run: flutter config --enable-web
    - run: flutter build web --target "./lib/main_development.dart"
